### ISSUE TITLE
Problem with having Name in the rheology structs

### ISSUE THREAD

**Issue by albert-de-montserrat** [JuliaGeodynamics/GeoParams.jl#122]
Thanks to @tduretz testing we have realised that having the name of the rheology in the `AbstractCreepLaw` types makes the code type-unstable. For example something like

```julia
function main()
   x = DislocationCreep()
   for i in 1:10
      # do some calculation with x
   end
end
```
will make every iteration allocate. Looks like the whole problem comes from the conversion of `Name` from `String` to `NTuple{N,Char}` because `N` is the length of `Name` and is unknown at compile time. Same problem applies to e.g. `MaterialParams`.

Having `Name` in the object also has another problem, which is that it increases the size of these `struct` to the point that a CUDA kernel will fail to compile if there are many material phases passed into it.

I would propose to just remove `Name` from these objects. I guess an user could simple make a dictionary to map `Phase::Int64` in `MaterialParams` to phase/creep law name if he wants this information.

@boriskaus  any thoughts?

**Comment by albert-de-montserrat** [comment]
For the creeps laws, maybe we could identify them with an integer instead. `Name=0` if they are not from the database, and `Name=x::Int` if they are from the database, then just provide a `get_name`  function to map the integer to the string.

**Comment by boriskaus** [comment]
Hmm, we converted that because it is otherwise not `isbittype`. Is it not possible to encode `N` in the type name as well? I quite like having the name in the struct but if there is no other way we can do it as you suggest

**Comment by albert-de-montserrat** [comment]
A simple workaround may be to just use `Adapt.jl` and leave the name as a `String`. This does the trick

```julia
struct F1{T}
    x::T
    str::String
end
Adapt.@adapt_structure F1

A = F1(1, "potato")

@parallel_indices (i,j) function f(x, A)
    x[i,j] *= 2
    return nothing
end

@parallel (1:2,1:2) f(@rand(2,2), A) # works
```

**Comment by boriskaus** [comment]
That would do it as well; requires us to change this in a few places
