### ISSUE TITLE
Nondimensionalizing a nondimensional variable leads to locking

### ISSUE THREAD

**Issue by ArneSpang** [JuliaGeodynamics/GeoParams.jl#197]
I sometimes forget attaching a unit to a variable and if I then try to nondimensionalize the variable, the code locks instead of throwing an error. Can we introduce an error message for this common user mistake where the input to nondimensionalize has no unit?

Example:
using GeoParams
CD = GEO_units(length=10km, temperature=600C, stress=1000MPa, viscosity=1e20Pas)
m = 5 # forgot to add kilogram here
nondimensionalize(m, CD) # the code will hang here for eternity

**Comment by albert-de-montserrat** [comment]
For some reason, throwing when the number is unitless breaks some internal stuff. Would it be ok for you to instead of throwing, to return the unitless number instead? Could add a warning in this case.

**Comment by ArneSpang** [comment]
> For some reason, throwing when the number is unitless breaks some internal stuff. Would it be ok for you to instead of throwing, to return the unitless number instead? Could add a warning in this case.

Ah that's a bummer. I think in this case, it is better for it to lock than continue with a wrong value because warnings can easily be overlooked in the output. At least in my case, this always happens because I forgot to add the unit and not because I used it on an already dimensionless parameter. So I want it to not run.

So, if error message won't work, can we add the warning and keep the locking behavior? Then, you would always see the warning at the bottom of the output and know why it is stuck.

**Comment by albert-de-montserrat** [comment]
I guess a warning + hanging is not too far from crashing if you are running the job interactively. But if for example you are submitting a job in a cluster, you may not notice immediately that the job is actually hanging. So throwing/crashing sounds like the safest option.

@boriskaus any ideas? If I add the throwing error, the Perplex tests don't pass anymore.

**Comment by ArneSpang** [comment]
Not sure if you had time for this yet, but another trap is if you accidentally pass an empty vector to nondimensionalize(). This will also hang instead of crashing

**Comment by albert-de-montserrat** [comment]
Sorry forgot about this issue... I'm taking a look again to find a workaround

**Comment by albert-de-montserrat** [comment]
By empty vector, do you mean something like `Float64[]` or the more generic `[]`?
